### ISSUE TITLE
通过Docker进行部署

### ISSUE THREAD

**Issue by Limour-dev** [Limour-dev/chatgpt-demo#1]
# 安装docker
nano /etc/docker/daemon.json 添加的内容
```json
{
    "registry-mirrors":[
                        "https://hub-mirror.c.163.com/",
                        "https://docker.mirrors.ustc.edu.cn/"
                        ]
}
```
- curl -sSL https://get.daocloud.io/docker | sh
- curl -L https://get.daocloud.io/docker/compose/releases/download/v2.16.0/docker-compose-$(uname -s)-$(uname -m) > /usr/local/bin/docker-compose
- chmod +x /usr/local/bin/docker-compose
- docker -v
- docker-compose -v
- nano /etc/docker/daemon.json
- systemctl daemon-reload
- systemctl restart docker

# 安装chatgpt-demo
 nano Dockerfile 添加的内容
```Dockerfile
FROM node:alpine
COPY chatgpt-demo /app
WORKDIR /app
RUN npm config set registry https://registry.npmmirror.com \
 && npm install
ENV PORT=3000
CMD ["npm", "run", "dev", "--", "--port", "3000", "--host", "0.0.0.0"]
```
 nano docker-compose.yml 添加的内容
```yml
version: '3.3'
services:
    chatgpt:
        container_name: chatgpt
        restart: always
        image: limour/chatgpt
        ports:
            - '6903:3000'
        volumes:
            - ./.env:/app/.env
```

- mkdir -p ~/app/chatGPT && cd ~/app/chatGPT && nano Dockerfile && nano docker-compose.yml
- git clone --depth=1 https://ghproxy.com/https://github.com/Limour-dev/chatgpt-demo.git
- cp ./chatgpt-demo/.env.example .env && nano .env # 填上自己的key 和 自己反代的api地址
- 自己反代的api的方法：[利用Golang反代某AI的API](https://occdn.limour.top/2607.html)
- sudo docker build -t limour/chatgpt .
- sudo docker-compose up -d && sudo docker-compose logs

# 容器内安装git
```bash
sudo docker-compose exec chatgpt sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
sudo docker-compose exec chatgpt apk update
sudo docker-compose exec chatgpt apk add git
```

# 容器内更新chatgpt-demo
```bash
sudo docker-compose exec chatgpt git pull 
sudo docker-compose exec chatgpt npm install
```
